---
- name: restart postgresql
  service:
    name: postgresql
    state: restarted

- name: restart fifoci supervisor
  supervisorctl:
    name: gunicorn_fifoci
    state: restarted

- name: restart central supervisor
  supervisorctl:
    name: central
    state: restarted

- name: restart supervisor
  service:
    name: supervisor
    state: restarted

- name: restart buildbot
  service:
    name: buildmaster
    state: restarted
    enabled: yes
    pattern: "--python=buildbot.tac"

- name: restart nginx
  service:
    name: nginx
    state: restarted

