# under vagrant user
---
- name: Install pip
  sudo: yes
  easy_install: name=pip

- name: Check homebrew installation
  stat: path=/usr/local/bin/brew
  register: brew_exec

- name: Get homebrew installer
  copy: src=homebrew/install dest=~/install_homebrew
  when: not brew_exec.stat.exists

- name: Install homebrew
  shell: "echo \"\\n\" | ruby install_homebrew"
  when: not brew_exec.stat.exists

- name: Update brew cache and upgrade
  homebrew: update_homebrew=yes upgrade_all=yes

