---
- name: Add buildbot user
  user:
    name: "{{ buildslave_username }}"
    state: present
    shell: /bin/bash
    home: "/home/{{ buildslave_username }}"

- name: Add public key to login as buildbot
  authorized_key: user=buildbot key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

