---
- name: Add buildbot user
  user:
    name: buildbot
    state: present
    shell: /bin/bash
    home: /home/buildbot

- name: Add public key to login as buildbot
  authorized_key: user=buildbot key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

