---
- name: Install common build dependencies
  apt: pkg={{ item }} state=present
  with_items:
    - cmake
    - g++
    - git
    - libgtk2.0-dev
    - libbluetooth-dev
    - libxrandr-dev
    - libxext-dev
    - libreadline-dev
    - libpulse-dev
    - libao-dev
    - libopenal-dev
    - libavcodec-dev
    - libavformat-dev
    - libswscale-dev
    - mercurial # this is to install the latest SDL

- name: Install debian specific build dependencies
  apt: pkg={{ item }} state=present
  with_items:
    - libwxbase2.8-dev
    - libwxgtk2.8-dev
    - libasound2-dev
    - libgl1-mesa-dev
    - libglu1-mesa-dev
    - libxt-dev
    - libxt6
    - mesa-common-dev
  when: ansible_distribution == 'Debian'

- name: Install ubuntu specific build dependencies
  apt: pkg={{ item }} state=present
  with_items:
    - libwxbase3.0-dev
    - libwxgtk3.0-dev
    - libasound-dev
  when: ansible_distribution == 'Ubuntu'

# SDL 2.0 must be compiled from source to prevent a bug causing Dolphin to crash
# with rumble-enabled conrollers.
- name: Retrieve SDL
  hg: repo=http://hg.libsdl.org/SDL dest=~/SDL

- name: Install SDL
  shell: "./configure && make -j4 && make install"
  args:
    chdir: ~/SDL
    creates: /usr/local/include/SDL2/SDL.h
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

