---
- name: Add github to known_hosts
  sudo: yes
  sudo_user: "{{ buildmaster_username or buildslave_username }}"
  lineinfile:
    dest: ~/.ssh/known_hosts
    create: yes
    state: present
    line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
    regexp: "^github\\.com"

