---
- name: Set up mirror
  template: src=etc_apt_sources.list.{{ ansible_distribution }}.j2 dest=/etc/apt/sources.list backup=yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

# When run in virtualbox where apt is cached, only update the cache on the main
# apt hosts. Other hosts on the same OS version will re-use it.
- name: Update apt cache
  apt: update_cache=yes
  when: ansible_hostname in groups['aptmaster']

- name: Upgrade all safe packages
  apt: upgrade=safe

- name: Install base packages
  apt: pkg={{ item }} state=present
  with_items:
    - apt-transport-https
    - sudo
    - vim
    - git

- name: Install unattended upgrades (Debian/Ubuntu only)
  apt: pkg=unattended-upgrades state=present
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

