---
- name: Wait for WinRM
  local_action: wait_for port="{{ ansible_ssh_port }}" host="{{ inventory_hostname }}"

##
## Remove applications
##
- name: Checking common setup
  win_stat:
    path: .common
  register: common

- name: Install removal utilitiies
  win_copy:
    src: "files/{{ item }}"
    dest: "c:/tmp/{{ item }}"
  with_items:
    - BlockWindows.bat
    - HideWindowsUpdates.vbs
    - uninstall_apps.ps1
  when: not common.stat.exists

- name: Execute telemetry removal
  raw: "c:\\tmp\\BlockWindows.bat"
  when: not common.stat.exists

- name: Uninstall Windows Modern Apps
  raw: "powershell c:\\tmp\\uninstall_apps.ps1"
  when: not common.stat.exists

- name: Remove removal utilities
  win_file:
    path: "c:/tmp/{{ item }}"
    state: absent
  with_items:
    - BlockWindows.bat
    - HideWindowsUpdates.vbs
    - uninstall_apps.ps1
  when: not common.stat.exists

- name: Removal complete
  win_file:
    name: .common
    state: touch
  when: not common.stat.exists

##
## Stop services
##
- name: Stop unnecessary services
  win_service:
    name: "{{ item }}"
    start_mode: disabled
    state: stopped
  with_items:
    - Spooler
    - WSearch
    - WSService

