---
- name: Copy base hosts file for unix
  copy:
    src: hosts.unix
    dest: ~/hosts
  when: ansible_hostname in groups['unix']

- name: Add servers to unix /etc/hosts
  shell: "cat ~/hosts >> {{ etc_hosts_file }}"
  when: ansible_hostname in groups['unix']

- name: Add servers to windows /etc/hosts
  raw: "type c:\\vagrant\\ansible\\roles\\common\\files\\hosts.windows >> {{ etc_hosts_file }}"
  when: ansible_hostname in groups['windows']

