---
- include: common_Debian.yml tags=common,debian
  when: ansible_os_family == 'Debian'

- include: common_Darwin.yml tags=common,darwin
  when: ansible_os_family == 'Darwin'

- include: common_Windows.yml tags=common,windows
  when: ansible_os_family == 'Windows'

