---
- include: apt.yml tags=pkg
  when: ansible_os_family == 'Debian'

- include: ntp.yml tags=ntp
  when: ansible_os_family == 'Debian'

- include: hosts.yml tags=hosts

#- include: security.yml tags=security

