---
- name: Buildmaster service state change
  service:
    name: buildmaster
    state: "{{ buildbot_state }}{{ 'ped' if buildbot_state == 'stop' else 'ed' }}"
    enabled: yes
    pattern: "--python=buildbot.tac"
  when: ansible_hostname in groups['buildmaster']

- name: Linux buildslave service state change
  service:
    name: buildslave
    state: "{{ buildbot_state }}{{ 'ped' if buildbot_state == 'stop' else 'ed' }}"
    enabled: yes
    pattern: /usr/bin/buildslave
  when: ansible_system == 'Linux' and ansible_hostname not in groups['buildmaster']

- name: FreeBSD buildslave service state change
  service:
    name: buildslave
    state: "{{ buildbot_state }}{{ 'ped' if buildbot_state == 'stop' else 'ed' }}"
    enabled: yes
    pattern: /usr/local/bin/buildslave
  when: ansible_system == 'FreeBSD' and ansible_hostname not in groups['buildmaster']

# The service module does not support OSX
# - name: OSX buildslave service state change
#   service:
#     name: net.buildbot.slave
#     enabled: yes
#     pattern: "buildbot.tac"
#     state: restarted
#   when: ansible_system == 'Darwin'
#   ignore_errors: yes
# So fake it.
# (must sudo because osx is run as vagrant user)
- name: OSX buildslave service state change
  become: yes
  shell: "launchctl {{ 'un' if buildbot_state == 'stop' else '' }}load -w /Library/LaunchAgents/net.buildbot.slave.plist"
  when: ansible_system == 'Darwin'

- name: Windows buildslave service state change
  win_service:
    name: BuildBot
    start_mode: auto
    state: "{{ buildbot_state }}{{ 'ped' if buildbot_state == 'stop' else 'ed' }}"
  when: ansible_os_family == 'Windows'

