---
##
## APT DEPENDENCIES
##
- name: nginx | Install nginx
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - nginx

##
## NGINX
##
- name: nginx | Install nginx.conf
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: nginx | Link nginx log location
  file:
    src: /var/log/nginx
    dest: /usr/share/nginx/logs
    state: link

- name: nginx | Create nginx services area
  command: mkdir /etc/nginx/services
  args:
    creates: /etc/nginx/services

- name: nginx | Create nginx SSL area
  file:
    path: /etc/nginx/ssl
    mode: 0755
    state: directory
    recurse: yes

- name: nginx | Create Self-Signed SSL certificate
  command: "openssl req -newkey rsa:2048 -new -nodes -x509 -days 3650 -keyout {{ ansible_hostname }}.key -out {{ ansible_hostname }}.pem -subj '/CN=*.dev'"
  args:
    chdir: /etc/nginx/ssl
    creates: "/etc/nginx/ssl/{{ ansible_hostname }}.pem"

- name: nginx | Get ssl certificate for master deployment
  fetch:
    src: "/etc/nginx/ssl/{{ ansible_hostname }}.pem"
    dest: "tmp/ssl/{{ ansible_hostname }}.crt"
    flat: yes
    fail_on_missing: yes
    validate_checksum: yes

- name: nginx | Start nginx
  service:
    name: nginx
    state: started
    enabled: yes

