---
# No ssh in windows as such. Ansible's windows remote access is via winrm which
# re-uses these ssh values.
ansible_ssh_user: vagrant
ansible_ssh_pass: vagrant
ansible_ssh_port: 5985
ansible_connection: winrm

etc_hosts_file: 'c:\windows\system32\drivers\etc\hosts'

# Where the installation files are located remotely.
cache_location: 'c:\tmp\vagrant-cache'

# Where installation files are located locally.
# Windows has problems installing certain file types from a network drive.
download_location: 'c:\tmp'

# Git for windows
git_file: Git-2.7.0-64-bit.exe

# Visual Studio ISO
vs_file: vs2015.1.com_enu.iso
vs_version: 14.0

# 7zip for windows
zip_file: 7z1514-x64.msi

# Python for windows. This must be version 2 due to buildbot.
python_file: python-2.7.11.amd64.msi

# python win32 extensions.
pywin32_file: pywin32-219.win-amd64-py2.7.exe

# Windows Development Kit
wdk_file: wdksetup.exe
