---
- name: Add buildbot user
  user:
    name: "{{ buildbot_username }}"
    state: present
    shell: /bin/bash
    home: "/home/{{ buildbot_username }}"

- name: Add public key to login as buildbot
  authorized_key:
    user: "{{ buildbot_username }}"
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

