---
##
## USER
##
- name: buildbot | Add buildbot user
  user:
    name: "{{ buildbot_username }}"
    home: "/home/{{ buildbot_username }}"
    shell: /bin/bash
    state: present

- name: buildbot | Add public key to login as buildbot
  authorized_key:
    user: "{{ buildbot_username }}"
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

# buildmaster will change into fifoci to upload the test results fetched from
# the fifoci slave into the fifoci (master) front end.
- name: buildbot | Give buildmaster sudo
  copy:
    content: "{{ buildbot_username }} ALL=(ALL) NOPASSWD: ALL"
    dest: "/etc/sudoers.d/{{ buildbot_username }}"
    mode: 0440
    validate: "visudo -cf %s"

##
## APT DEPENDENCIES
##
- name: buildbot | Install buildbot-master
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - buildbot
    - python
    - python-pip
    - python-dev

##
## PIP DEPENDENCIES
##
- name: buildbot | Install python packages (pip)
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - psycopg2

##
## DEPLOY
##
- name: buildbot | Create bin directory
  sudo: yes
  sudo_user: "{{ buildbot_username }}"
  file:
    path: ~/bin
    state: directory

- name: buildbot | Install send_build.py
  sudo: yes
  sudo_user: "{{ buildbot_username }}"
  copy:
    src: sadm/buildbot/send_build.py
    dest: ~/bin/send_build.py
    mode: 0755

##
## POSTGRESQL
##
- name: buildbot | create buildbot database user
  sudo: yes
  sudo_user: postgres
  postgresql_user:
    name: "{{ buildbot_username }}"
    password: "{{ buildbot_username }}"

- name: buildbot | Create buildbot database
  sudo: yes
  sudo_user: postgres
  postgresql_db:
    owner: "{{ buildbot_username }}"
    name: "{{ buildbot_username }}"
    state: present

- name: buildbot | Grant database access
  sudo: yes
  sudo_user: postgres
  postgresql_privs:
    db: "{{ buildbot_username }}"
    privs: ALL
    type: database
    role: "{{ buildbot_username }}"

##
## BUILDBOT
##
- name: buildbot | Create build master
  sudo: yes
  sudo_user: "{{ buildbot_username }}"
  command: "buildbot create-master --db postgresql://buildbot@localhost/buildbot"
  args:
    creates: buildbot.tac

# Bug in buildbot 0.8.x (fixed in 0.9.x) with postgresql
# It can cause changes that should be added to the build queue to go missing.
# http://trac.buildbot.net/ticket/2423
- name: buildbot | Workaround buildbot race condition
  sudo: yes
  sudo_user: "{{ buildbot_username }}"
  command: psql -c "alter table buildsets drop constraint buildsets_sourcestampid_fkey"

- name: buildbot | Install master.cfg
  sudo: yes
  sudo_user: "{{ buildbot_username }}"
  copy:
    src: sadm/buildbot/master.cfg
    dest: ~/master.cfg
    mode: 0444

- name: buildbot | Customise dolphin repository
  sudo: yes
  sudo_user: "{{ buildbot_username }}"
  lineinfile:
    backup: yes
    dest: ~/master.cfg
    state: present
    regexp: ^DOLPHIN_REPO
    line: "DOLPHIN_REPO = \"{{ dolphin_repository }}\""

# Do not parameterise the password file creation. The passwords will print to
# stdout in the ansible output.
- name: buildbot | Build buildslave password file
  sudo: yes
  sudo_user: "{{ buildbot_username }}"
  copy:
    content: "{{ buildslaves_passwords | to_nice_json }}"
    dest: ~/buildslaves-passwords.json

- name: buildbot | Build users password file
  sudo: yes
  sudo_user: "{{ buildbot_username }}"
  copy:
    content: "{{ buildmaster_users_passwords | to_nice_json }}"
    dest: ~/users-passwords.json

- name: buildbot | Build changesource password file
  sudo: yes
  sudo_user: "{{ buildbot_username }}"
  copy:
    content: "{{ changesource_password }}"
    dest: ~/changesource-password.txt

- name: buildbot | Build webauth password file
  sudo: yes
  sudo_user: "{{ buildbot_username }}"
  copy:
    content: "{{ webauth_password }}"
    dest: ~/webauth-password.txt

- name: buildbot | Enable buildmaster init.d
  template:
    src: etc_default_buildmaster.j2
    dest: /etc/default/buildmaster
    backup: yes
    mode: 0444

- name: buildbot | Start buildmaster
  service:
    name: buildmaster
    state: restarted
    enabled: yes
    pattern: "--python=buildbot.tac"

##
## WEB
##
- name: buildbot | Enable nginx proxy
  template:
    src: buildbot.nginx.j2
    dest: /etc/nginx/services/buildbot.nginx
    mode: 0444
  notify: restart nginx

