---
##
## USER
##
- name: central | Add central user
  user:
    name: central
    state: present
    shell: /bin/bash
    home: /home/central

- name: central | Add public key to login as central
  authorized_key:
    user: central
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

##
## APT DEPENDENCIES
##
- name: central | Install central dependencies
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - python3
    - python3-pip
    - supervisor

##
## DEPLOY
##
- name: central | Install central
  shell: cp -R ~/sadm/central/* /home/central && chown -R central:central /home/central
  args:
    creates: /home/central/central.py

- name: central | Disable modules
  sudo: yes
  sudo_user: central
  lineinfile:
    dest: "/home/central/{{ item }}.py"
    state: present
    insertafter: '^def\s*start\(\)'
    line: '    return'
    backup: yes
  with_items:
    - gcodepoller
    - github

##
## PIP DEPENDENCIES
##
- name: central | Install central dependencies (pip requirements)
  pip:
    executable: pip3
    requirements: /home/central/requirements.txt

##
## WEB
##
- name: central | Install configuration file
  sudo: yes
  sudo_user: central
  template:
    src: central_config.yml.j2
    dest: ~/config.yml

- name: central | Install the supervisor configuration file
  template:
    src: supervisor.central.conf.j2
    dest: /etc/supervisor/conf.d/central.conf
    mode: 0444
  notify: restart supervisor

- name: central | Enable nginx proxy
  template:
    src: central.nginx.j2
    dest: /etc/nginx/services/central.nginx
    mode: 0444
  notify: restart nginx

