---
##
## USER
##
- name: changes | Add changes user
  user:
    name: changes
    home: /home/changes
    shell: /bin/bash
    state: present

- name: changes | Add public key to login as changes
  authorized_key:
    user: changes
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

- name: changes | Add github to known_hosts
  become: yes
  become_user: changes
  lineinfile:
    dest: ~/.ssh/known_hosts
    create: yes
    state: present
    line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
    regexp: "^github\\.com"

##
## DEPLOY
##
- name: changes | Install changes
  shell: cp -p -R ~/sadm/changes/* /home/changes && chown -R changes:changes /home/changes
  args:
    creates: /home/changes/gen-pages

- name: changes | Replace wiki.dolphin-emu.org
  become: yes
  become_user: changes
  replace:
    dest: "/home/changes/update-wiki"
    regexp: 'dolphin-emu\.org'
    replace: "dev"
    backup: yes

- name: changes | Replace number of revisions to check
  become: yes
  become_user: changes
  replace:
    dest: "/home/changes/gen-rev-infos"
    regexp: '-n 100'
    replace: "-n {{ changes_revision_count }}"
    backup: yes

- name: changes | Update configuration
  become: yes
  become_user: changes
  template:
    src: changes.config.vars.j2
    dest: ~/config.vars

- name: changes | Create changes web area
  file:
    path: "{{ changes_web_location }}"
    owner: changes
    group: changes
    mode: 0755
    state: directory
    recurse: yes

# There is no need to clone the submodules since only the dolphin changes are of
# interest.
- name: changes | Create dolphin (non-recursive) clone on which changes operates
  become: yes
  become_user: changes
  git:
    repo: "{{ dolphin_repository }}"
    dest: "{{ changes_dolphin_location }}"
    accept_hostkey: "{{ 'yes' if testing is defined else 'no' }}"
    recursive: no

##
## CRON
##
- name: changes | Install changes cron
  cron:
    name: "check for dolphin changes"
    job: "/home/changes/gen-pages >/dev/null"
    state: present
    user: changes

##
## WEB
##
- name: changes | Enable nginx proxy
  template:
    src: changes.nginx.j2
    dest: /etc/nginx/services/changes.nginx
    mode: 0444
  notify: restart nginx

