---
##
## APT DEPENDENCIES
##
- name: database | Install database
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - postgresql
    - libpq-dev

##
## CONFIGURATION
##
- name: database | Update pg_hba.conf
  replace:
    dest: /etc/postgresql/9.4/main/pg_hba.conf
    regexp: '^(host\s+all\s+all\s+{{ item }}\s+)md5$'
    replace: '\1trust'
    backup: yes
  with_items:
    - 127.0.0.1/32
    - ::1/128

# Restart has to happen immediately for provisioning since handlers happen at
# the end.
- name: database | restart
  service:
    name: postgresql
    state: restarted

