---
- name: Create dl area
  shell: mkdir -p /srv/http/dl

- name: Enable nginx proxy
  template: src=dl.nginx.j2 dest=/etc/nginx/services/dl.nginx mode=0444
  when: ansible_os_family == 'Debian'
  notify: restart nginx

