---
- name: dl | Create dl web area
  file:
    path: "{{ buildmaster_builds_location }}/builds"
    owner: "{{ buildbot_username }}"
    group: "{{ buildbot_username }}"
    mode: 0755
    state: directory
    recurse: yes

- name: dl | Enable nginx proxy
  template:
    src: dl.nginx.j2
    dest: /etc/nginx/services/dl.nginx
    mode: 0444
  notify: restart nginx

