---
##
## CLONE
##
- name: master | Add github to known_hosts
  lineinfile:
    dest: ~/.ssh/known_hosts
    create: yes
    state: present
    line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
    regexp: "^github\\.com"

- name: master | Clone sadm
  git:
    repo: "{{ sadm_repository }}"
    dest: sadm
    accept_hostkey: "{{ 'yes' if testing is defined else 'no' }}"
    force: yes
    depth: 1

- include: database.yml
  tags: database
- include: nginx.yml
  tags: nginx
- include: buildmaster.yml
  tags: buildbot
- include: central.yml
  tags: central
- include: dl.yml
  tags: dl
- include: fifoci.yml
  tags: fifoci
- include: changes.yml
  tags: changes

# Force handlers so the web sites are accessible
- meta: flush_handlers

