---
##
## APT DEPENDENCIES
##
- name: nginx | Install nginx
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - nginx

##
## NGINX
##
- name: nginx | Install nginx.conf
  shell: cp ~/sadm/nginx/nginx.conf /etc/nginx/nginx.conf

- name: nginx | Specify nginx pid location
  lineinfile:
    dest: /etc/nginx/nginx.conf
    state: present
    insertbefore: BOF
    line: "pid /run/nginx.pid;"

- name: nginx | Change nginx user
  lineinfile:
    dest: /etc/nginx/nginx.conf
    state: present
    regexp: "^user http;"
    line: "user www-data;"

- name: nginx | Link nginx log location
  file:
    src: /var/log/nginx
    dest: /usr/share/nginx/logs
    state: link

- name: nginx | Create nginx services area
  file:
    path: /etc/nginx/services
    state: directory

- name: nginx | Create nginx SSL area
  file:
    path: /etc/nginx/ssl
    state: directory

# The name of the certificate and key comes from sadm/nginx/ngix.conf.
- name: nginx | Create Self-Signed SSL certificate
  command: "openssl req -newkey rsa:2048 -new -nodes -x509 -days 3650 -keyout dolphin-emu.key -out dolphin-emu.pem -subj '/CN=*.dev'"
  args:
    chdir: /etc/nginx/ssl
    creates: "/etc/nginx/ssl/dolphin-emu.pem"

- name: nginx | Get ssl certificate for slave deployment
  fetch:
    src: "/etc/nginx/ssl/dolphin-emu.pem"
    dest: "tmp/ssl/dolphin-emu.crt"
    flat: yes
    fail_on_missing: yes
    validate_checksum: yes

- name: nginx | Start nginx
  service:
    name: nginx
    state: started
    enabled: yes

