---
# sudo because on osx the playbook is not run as root
- name: Install buildbot slave
  sudo: yes
  pip: name=buildbot-slave executable=/usr/local/bin/pip

- name: Create build slave
  shell: /usr/local/bin/buildslave create-slave . {{ buildmaster_host }}:{{ buildmaster_port }} {{ slave_username }} {{ slave_password }}
  args:
    creates: buildbot.tac

- name: Update slave admin information
  template: src=buildbot_info_admin.j2 dest=info/admin

# ignore errors in case the master is not yet started
- name: Start slave (non-service)
  shell: "nohup nice /usr/local/bin/buildslave restart"
  ignore_errors: True

