---
- name: dpkg | Install template files
  become: yes
  become_user: "{{ buildbot_username }}"
  copy:
    src: dpkg/
    dest: ~/debian/

# For some reason, copy does not copy the file attributes.
- name: dpkg | Fix file attributes post-copy
  become: yes
  become_user: "{{ buildbot_username }}"
  file:
    path: debian/rules
    mode: 0755
    state: file

# Ansible emits a warning about using unarchive rather than tar.
# It is wrong. This task creates an archive; it is not unarchiving one.
- name: dpkg | Create template archive for buildbot (ignore any warning)
  become: yes
  become_user: "{{ buildbot_username }}"
  shell: "tar czf dolphin-debian.tar.gz debian/"
  args:
    creates: ~/dolphin-debian.tar.gz

