---
- include: windows_cache_download.yml

- name: 7zip | Installed?
  win_stat:
    path: "C:\\Program Files\\7-Zip"
  register: app

- name: 7zip | Install
  win_msi:
    path: "{{ download_location }}\\{{ file }}"
    state: present
  when: not app.stat.exists

- name: 7zip | Add to path
  raw: "powershell [Environment]::SetEnvironmentVariable('Path', $env:Path + ';C:\\Program Files\\7-Zip', [EnvironmentVariableTarget]::Machine)"
  when: not app.stat.exists

