---
- include: windows_cache_download.yml

- name: git | Installed?
  win_stat:
    path: "C:\\Program Files\\Git"
  register: app

- name: git | Install
  raw: "{{ download_location }}\\{{ file }} /SILENT"
  when: not app.stat.exists

- name: git | Add to path
  raw: "powershell [Environment]::SetEnvironmentVariable('Path', $env:Path + ';C:\\Program Files\\Git\\bin', [EnvironmentVariableTarget]::Machine)"
  when: not app.stat.exists

