---
- name: git | Installed?
  win_stat:
    path: "C:\\Program Files\\Git"
  register: app

- name: git | Install
  win_package:
    name: git
    path: "{{ download_location }}\\{{ file }}"
    product_id: "Git_is1"
    arguments: "/SILENT"
  when: not app.stat.exists
