---
- name: python | Installed?
  win_stat:
    path: "C:\\Python27"
  register: app

- name: python | Install
  win_msi:
    path: "{{ download_location }}\\{{ file }}"
    state: present
  when: not app.stat.exists

- name: python | Revert secure https that doesn't use system certificates
  win_copy:
    src: files/sitecustomize.py
    dest: c:/Python27/Lib/site-packages/sitecustomize.py

