---
- include: windows_cache_download.yml

- name: python | Installed?
  win_stat:
    path: "C:\\Python27"
  register: app

- name: python | Install
  win_msi:
    path: "{{ download_location }}\\{{ file }}"
    state: present
  when: not app.stat.exists

- name: python | Add to path
  raw: "powershell [Environment]::SetEnvironmentVariable('Path', $env:Path + ';C:\\Python27;C:\\Python27\\Scripts', [EnvironmentVariableTarget]::Machine)"
  when: not app.stat.exists

