---
- name: pywin32 | Installed?
  win_stat:
    path: "C:\\python27\\scripts\\pywin32_postinstall.py"
  register: app

- name: pywin32 | Install
  raw: "c:\\python27\\scripts\\easy_install {{ download_location }}\\{{ file }}"
  when: not app.stat.exists

