# No ansible support for git on windows.
---
- name: Clone Qt
  raw: "git clone {{ ext_win_qt_repository }} C:\\Qt"
  ignore_errors: yes

- name: Add QTDIR path
  win_environment:
    name: QTDIR
    value: 'C:\Qt\Qt5.5.0\5.5\msvc2015_64_opengl'
    level: machine
