---
# Get the installer either from the cache or from an external source.
# Cache it if it was fetched externally.
- name: Is local file present?
  win_stat:
    path: "{{ download_location }}/{{ file }}"
  register: file_downloaded

# Pull file from the cache if the file is not in the download area
- name: Is file cached?
  win_stat:
    path: "{{ cache_location }}/{{ file }}"
    get_md5: no
  register: file_cached
  when: not file_downloaded.stat.exists

- name: Copy cached file to download area
  raw: "copy {{ cache_location }}\\{{ file }} {{ download_location }}\\{{ file }}"
  when: not file_downloaded.stat.exists and file_cached.stat.exists

# Download when the file doesn't exist locally or in the cache
- name: Download file
  win_get_url:
    url: "{{ base_url }}/{{ file }}"
    dest: "{{ download_location }}/{{ file }}"
  when: not file_downloaded.stat.exists and not file_cached.stat.exists

- name: Copy downloaded file to cache
  raw: "copy {{ download_location }}\\{{ file }} {{ cache_location }}\\{{ file }}"
  when: not file_downloaded.stat.exists and not file_cached.stat.exists

