---
- name: Install uninstallation utility
  raw: "copy c:\\vagrant\\ansible\\roles\\windows\\files\\uninstall_apps.ps1 c:\\tmp"

- name: Uninstall Windows Modern Apps
  raw: "powershell c:\\tmp\\uninstall_apps.ps1"

# turn off windows store tile
- name: Create PushNotification registry entry
  raw: "powershell New-Item -path Registry::HKEY_CURRENT_USER\\Software\\Policies\\Microsoft\\Windows\\CurrentVersion\\PushNotifications"

- name: Set tile PushNotification disabled
  raw: "powershell New-ItemProperty -path Registry::HKEY_CURRENT_USER\\Software\\Policies\\Microsoft\\Windows\\CurrentVersion\\PushNotifications -Name NoTileApplicationNotification -PropertyType DWord -Value 0"

- name: Delete metro app caches
  raw: "rm -rf c:\\users\\{{ ansible_ssh_user }}\\appdata\\local\\packages"

- name: Stop unnecessary services
  win_service:
    name: "{{ item }}"
    start_mode: disabled
    state: stopped
  with_items:
    - Spooler
    - WSearch
    - WSService

